# Generated by Django 3.0.3 on 2020-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverName', models.CharField(max_length=60)),
                ('serverOS', models.CharField(max_length=100)),
                ('serverLogicalDrive', models.CharField(max_length=20)),
                ('serverProcessors', models.CharField(max_length=20)),
                ('serverRam', models.CharField(max_length=40)),
                ('serverLocation', models.TextField()),
                ('serverIpInternal', models.GenericIPAddressField()),
                ('serverSubnetMask', models.GenericIPAddressField()),
                ('serverGateway', models.GenericIPAddressField()),
                ('serverDns', models.CharField(max_length=50)),
                ('serverVlan', models.CharField(max_length=50)),
                ('serverIpExternal', models.GenericIPAddressField()),
                ('serverMns', models.CharField(max_length=100)),
            ],
        ),
    ]
